# Generated by Django 5.2.4 on 2025-08-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stocks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("date", models.DateField(max_length=200)),
                ("day_low", models.DecimalField(decimal_places=4, max_digits=10)),
                ("day_high", models.DecimalField(decimal_places=4, max_digits=10)),
                ("day_price", models.DecimalField(decimal_places=4, max_digits=10)),
                ("change", models.DecimalField(decimal_places=4, max_digits=10)),
                ("volume", models.IntegerField()),
            ],
        ),
    ]
